

services:
  web:
    image: nginx

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/frontend
      - ./certs:/etc/letsencrypt
    ports:
    - "80:80"
    - "443:443"
    # environment:
    #  - NGINX_HOST=foobar.com
    #  - NGINX_PORT=80
    networks:
      - backend



  auth-service:
    build: ./auth_service/
    ports:
    - 8080
    # - 8080:8080
    volumes:
      - ./auth_service:/app
      - ./shared:/app/shared
    networks:
      - backend


  user-service:
    build: ./user_service/
    ports:
    - 8081
    # - 8081:8081
    volumes:
      - ./user_service:/app
      - ./shared:/app/shared
    networks:
      - backend


  chat-service:
    build: ./chat_service/
    ports:
    - 8082
    # - 8082:8082
    volumes:
      - ./chat_service:/app
      - ./shared:/app/shared
    networks:
      - backend

    
    
    
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - 6379
  #   command: redis-server --bind 0.0.0.0 --protected-mode no

  redis:
    image: redis:latest
    expose:
      - "6379"
    networks:
      - backend
    command: redis-server


  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: a
      POSTGRES_USER: a
      POSTGRES_PASSWORD: a
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

      
volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
